server:
  port=8080




spring:
   datasource:
     url:jdbc:mysql://localhost:3306/productdb
     username=root
     password=root
     driver-class-name=com.mysql.jdbc.Driver

   jpa:
   database-platform : org.hibernate.dialect.MySQL5Dialect
   generate-ddl: true
   hibernate.ddl-auto : update